# (Default: true) Compatibility module for betternether@5.3.10(>=5.1.3)
betternether = false
# (Default: true) Compatibility module for betterend@0.12.2(>=0.10.2-pre)
betterend = true
# (Default: true) Compatibility module for charm@3.3.2(>=3.3.2)
charm = true

