GENERATE_OPAL_ORE = false

[END_GOBLIN_TRADER_CONFIG]
END_GOBLIN_TRADER_ALT_TEXTURE = false
HIT_BACK = true
END_GOBLIN_SPAWN_RATE_D = 1

[END_GOBLIN_TRADER_CONFIG.THE_OVERWORLD_SETTINGS]
MIN_HEIGHT = -64
MAX_HEIGHT = 255
CAN_SPAWN = false
SPAWN_CHANCE = 10
SPAWN_DELAY = 48000

[END_GOBLIN_TRADER_CONFIG.THE_NETHER_SETTINGS]
MIN_HEIGHT = 0
MAX_HEIGHT = 127
CAN_SPAWN = false
SPAWN_CHANCE = 25
SPAWN_DELAY = 32000

[END_GOBLIN_TRADER_CONFIG.THE_END_SETTINGS]
MIN_HEIGHT = 0
MAX_HEIGHT = 255
CAN_SPAWN = true
SPAWN_CHANCE = 45
SPAWN_DELAY = 24000
