MAX_ENCHANTMENT_TEXT = true
EASTER_EGGS = false

[ALL_GOBLIN_TRADERS_CONFIG]
FIND_COOLDOWN = 3600
FALL = true
NO_ATTACK_CREATIVE = true
CAN_GET_KNOCKED_OUT = true

[GOBLIN_TRADER_CONFIG]
CAN_SPAWN = true
HIT_BACK = true
SPAWN_CHANCE = 9
SPAWN_DELAY = 24000
MAX_SPAWN_HEIGHT = 20
MIN_SPAWN_HEIGHT = -64

[VEIN_GOBLIN_TRADER_CONFIG]
CAN_SPAWN = true
HIT_BACK = true
SPAWN_CHANCE = 2
SPAWN_DELAY = 24000
MAX_SPAWN_HEIGHT = -30
MIN_SPAWN_HEIGHT = -60
DAMAGED_IN_WATER = false
