[common]
debug = false
netherTop = 127
noEnergy = false
convertDeepslateOres = false
[power]
rebornEnergyConversionCoefficient = 0.0625
fastTransferEnergyConversionCoefficient = 0.0625
creativeGeneratorGeneration = 1000
[quarry]
quarryEnergyCapacity = 10000.0
quarryEnergyMakeFrame = 24.0
quarryEnergyBreakBlock = 25.0
quarryEnergyRemoveFluid = 60.0
quarryEnergyMoveHead = 0.5
[adv_pump]
advPumpEnergyCapacity = 1000.0
advPumpEnergyRemoveFluid = 30.0
[adv_quarry]
advQuarryEnergyCapacity = 50000.0
advQuarryEnergyMakeFrame = 30.0
advQuarryEnergyBreakBlock = 35.0
advQuarryEnergyRemoveFluid = 80.0
advQuarryEnergyMoveHead = 25.0
